version: "3.1"

services:
  myjenkins:
    build:
      context: .
    image: myjenkins
    ports:
     - "8083:8080"
    depends_on:
     #- mysonar
     - artifactory
    links:
      #- mysonar
      - artifactory
    volumes:
    # we use Vagrant on Windows and needs dirs outside windows mountpoint!
     - "/home/vagrant/jobs:/var/jenkins_home/jobs/"
     - "/home/vagrant/m2deps:/var/jenkins_home/.m2/repository/"
     - "./downloads:/var/jenkins_home/downloads"
    secrets:
     - artifactoryPassword
  # mysonar:
  #   image: sonarqube:6.3.1
  #   ports:
  #    - "9000"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.4.4
    ports:
     - "8081"
    volumes:
    # we use Vagrant on Windows and needs dirs outside windows mountpoint!
     - "artifactory_data:/opt/jfrog/artifactory/"

secrets:
  artifactoryPassword:
    file: ./secrets/artifactoryPassword

# List of all named volumes used
volumes:
  artifactory_data:
