version: "3.1"

services:
  myjenkins:
    image: kayan/myjenkins:latest
    ports:
     - "8080:8080"
    volumes:
     - "/home/vagrant/jobs:/var/jenkins_home/jobs/"
     - "/home/vagrant/m2deps:/var/jenkins_home/.m2/repository/"


